BFP-4038: Fix GET /account/valueHistory
removing schema type to make sure the python client works
with the enum oppose to a string, so that it won't run into
the following:

```
  File "/Users/kevinip/code/seedim/pro-sdk/python/example/main.py", line 159, in main
    account_value_history = await account_data_api.get_account_value_history(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinip/code/seedim/pro-sdk/python/sdk/src/openapi_client/api/account_data_api.py", line 1694, in get_account_value_history
    _param = self._get_account_value_history_serialize(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinip/code/seedim/pro-sdk/python/sdk/src/openapi_client/api/account_data_api.py", line 1885, in _get_account_value_history_serialize
    _query_params.append(('interval', interval.value))
                                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```